### PR TITLE
Changed API in accordance with #320.

### PR DESCRIPTION
**Pull request by ghost**
The old routes are still there, just deprecated.

Changed the API docs as well; the Apigee explorer will have to be updated separately.

Also see: https://github.com/nodester/nodester-api/pull/11

### CODE REVIEW

**Comment by chrismatthieu** [comment]
Awesome!  Your updates look great.  Does this update need to be rolled out at the same time as the -cli and -api updates?

**Comment by ghost** [comment]
This'll need to be rolled out **before** the -cli and -api updates. The latter two should continue to connect until they're updated, via the deprecated routes. Best if they're rolled out at around the same time, though.

-api will need a version bump and a resubmission to NPM; -cli will need the same, and a dependency version bump up to the new -api version. Other than that, there shouldn't be any changes needed to the -cli, at least for the #320 stuff. The other -api and -cli pull requests I have add in env accessors.

**Comment by chrismatthieu** [comment]
Nice! I will try to get these merged and deployed along with the updated npm modules this evening!  Thanks!

**Comment by nodester** [comment]
deployed and initial tests look good - nice job!

**Pull request merged**
