### PR TITLE
Fix for WebSockets draft-07

### PR DESCRIPTION
**Pull request by dvbportal**
This updates the proxy to handle WebSockets draft-07. Details can be found at https://github.com/nodejitsu/node-http-proxy/issues/97

### CODE REVIEW

**Comment by yocontra** [comment]
Thanks for the fix, will look at pulling it in right now. We're planning on switching to Bouncy (http://substack.net/posts/5bd18d/bounce-HTTP-requests-around-with-bouncy) since node-http-proxy has been giving us issues. This will at least fix the problem in the meantime.

**Comment by yocontra** [comment]
Pull no longer needed, we removed the proxy system this applies to.

**Comment by dvbportal** [comment]
Wow, the switch to Bouncy was fast. I hope I can follow soon.

**Comment by yocontra** [comment]
The guys behind bouncy make it very easy. It has a few quirks that need to be worked out but we'll send some information your way on migrating when it's perfected

**Pull request closed without merging**
