### PR TITLE
Here is the new cleaned up app.js

### PR DESCRIPTION
**Pull request by davglass**
Moved all routes into ./lib/

This way, you can have multiple people working on different parts with lower merge conflicts.

Various other cleanups too

### CODE REVIEW

**Comment by DanBUK** [comment]
Am about to go to a meetup Dave, but will try and merge this in tomorrow(GMT TZ). 

Thanks a lot!

**Comment by marcosvm** [comment]
I'm working on a testing suite for the api, so that's perfect to test both the merge and the test suite. Nice job guys.

**Comment by davglass** [comment]
Good, I was going to suggest that..

I also noted in the code that the /appdomain API is not right. It's a post that does add and delete. Shouldn't it be a POST and a DELETE to the same API?

**Comment by DanBUK** [comment]
Yes davglass it should be a DELETE action. I think maybe update should also be a PUT too :)

I'll look at modifying that once this is merged in.

**Comment by davglass** [comment]
Same goes for the /appnpm api. It's all in one for install, update, uninstall..

It should be:

post: install
delete: uninstall
put: update
get: ls

**Pull request merged**
